#!/usr/bin/env ruby
require "bundler/setup"
require "dry/cli"
require "readline"

module LostShip
  module CLI
    module Commands
      extend Dry::CLI::Registry

      class Start < Dry::CLI::Command
        require "lost_ship/models/game"
        desc "Start a game of W.M. Akers' “Lost Ship”"
        argument(
          :filename,
          default: ENV.fetch("LOST_SHIP_GAME", "./lost-ship.json"),
          desc: "Filename (default: #{ENV.fetch("LOST_SHIP_GAME", "./lost-ship.json")}) to write your game"
        )

        def call(filename:, **)
          puts "Starting a game of Lost Ship"
          ship_name = ::Readline.readline("Name your Colony ship: ", true)
          puts ""
          puts "Next name your six (6) scout ships:"
          scout_names = (1..6).map do |i|
            ::Readline.readline("\tScout ship #{i}: ", true)
          end
          puts ""
          puts "Next name your six (6) starting pilots:"
          pilot_names = (1..6).map do |i|
            ::Readline.readline("\tPilot #{i}: ", true)
          end
          puts ""
          puts "#{ship_name} (Empathy-class Colony Ship)"
          puts "Scout Ships: #{scout_names.join(', ')}"
          puts "Pilots: #{pilot_names.join(', ')}"

          game = Models::Game.start(
            ship_name: ship_name,
            pilot_names: pilot_names,
            scout_names: scout_names
          )
          game.write!(filename: filename)
        end
      end

      register "start", Start, aliases: ["s"]
    end
  end
end

Dry::CLI.new(LostShip::CLI::Commands).call
